name: GitHub Actions Minify
run-name: ${{ github.actor }} triggered minify action
on:
  push:
    branches:
      - 'flavio/minify'
      - '!main'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Minify
      uses: amireshoon/minifyAction@main
      with:
        repo: ${{ github.repository }}
    - name: Publish
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/flavio/minify' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
